#!/usr/bin/env python

import bectl
import crypt
import gi
import os
import gettext
import pwd
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

__VERSION__ = '0.1'

gettext.bindtextdomain('backup-station', '/usr/local/share/locale')
gettext.textdomain('backup-station')
_ = gettext.gettext


class BackupStationWindow(Gtk.Window):
    def create_be_list(self):
        data = bectl.get_be_list()
        data.pop(0)

        for element in data:
            self.liststore.append(element.split())

    def refresh_be_list(self):
        self.liststore.clear()
        self.create_be_list()

    def select_be(self):
        selection = self.treeview.get_selection()
        model, paths = selection.get_selected_rows()

        for path in paths:
            iter = model.get_iter(path)
            bename = model.get_value(iter, 0)

        return bename

    # Window and callback used to create a BE.
    def create_be_window(self, button):
        window = PopupEntryWindow(self.create_callback)
        window.show_all()

    def create_callback(self, text):
        bectl.create_be(text)
        self.refresh_be_list()

    # Window and callback used to rename a BE.
    def rename_callback(self, text):
        bename = self.select_be()
        bectl.rename_be(bename, text)
        self.refresh_be_list()

    def rename_be_window(self, button):
        window = PopupEntryWindow(self.rename_callback)
        window.show_all()

    def activate_be(self, button):
        bename = self.select_be()
        bectl.activate_be(bename)
        self.refresh_be_list()

    def delete_be(self, button):
        dialog = Gtk.MessageDialog(
            transient_for=self,
            flags=0,
            message_type=Gtk.MessageType.QUESTION,
            buttons=Gtk.ButtonsType.OK_CANCEL,
            title="Confirm Deletion",
            text="Are you sure you want to delete this BE?"
            )
        response = dialog.run()
        if response == Gtk.ResponseType.YES:
            bename = self.select_be()
            bectl.destroy_be(bename)
            self.refresh_be_list()

        dialog.destroy()


    def mount_be(self, button):
        bename = self.select_be()
        bectl.mount_be(bename)
        self.refresh_be_list()

    def umount_be(self, button):
        bename = self.select_be()
        bectl.umount_be(bename)
        self.refresh_be_list()

    def __init__(self):
        super().__init__(title=_("Backup Station"))

        self.set_resizable(False)

        # Create the liststore of boot environments.
        self.liststore = Gtk.ListStore(str, str, str, str, str, str)
        self.create_be_list()
        self.treeview = Gtk.TreeView(model=self.liststore)

        # Create columns for the data
        renderer_text = Gtk.CellRendererText()
        column_text = Gtk.TreeViewColumn(_("BE name"), renderer_text, text=0)
        self.treeview.append_column(column_text)

        column_text = Gtk.TreeViewColumn(_("Active"), renderer_text, text=1)
        self.treeview.append_column(column_text)

        column_text = Gtk.TreeViewColumn(_("Mountpoint"), renderer_text, text=2)
        self.treeview.append_column(column_text)

        column_text = Gtk.TreeViewColumn(_("Space"), renderer_text, text=3)
        self.treeview.append_column(column_text)

        column_text = Gtk.TreeViewColumn(_("Date"), renderer_text, text=4)
        self.treeview.append_column(column_text)

        column_text = Gtk.TreeViewColumn(_("Time"), renderer_text, text=5)
        self.treeview.append_column(column_text)

        # Create the buttons to manipulate the BE's
        create_button = Gtk.Button.new_with_label(_("Create BE"))
        create_button.connect("clicked", self.create_be_window)

        rename_button = Gtk.Button.new_with_label(_("Rename BE"))
        rename_button.connect("clicked", self.rename_be_window)

        activate_button = Gtk.Button.new_with_label(_("Activate BE"))
        activate_button.connect("clicked", self.activate_be)

        delete_button = Gtk.Button.new_with_label(_("Delete BE"))
        delete_button.connect("clicked", self.delete_be)

        mount_button = Gtk.Button.new_with_label(_("Mount BE"))
        mount_button.connect("clicked", self.mount_be)

        umount_button = Gtk.Button.new_with_label(_("Unmount BE"))
        umount_button.connect("clicked", self.umount_be)

        # Create boxes to hold the treeview columns and the row of buttons
        hbox = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
        hbox.pack_start(create_button, True, True, 2)
        hbox.pack_start(rename_button, True, True, 2)
        hbox.pack_start(delete_button, True, True, 2)
        hbox.pack_start(activate_button, True, True, 2)
        hbox.pack_start(mount_button, True, True, 2)
        hbox.pack_start(umount_button, True, True, 2)

        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        vbox.pack_start(self.treeview, True, True, 2)
        vbox.pack_start(hbox, True, True, 2)
        self.add(vbox)
        self.connect("destroy", Gtk.main_quit)


class PopupEntryWindow(Gtk.Window):
    def clicked(self, button):
        self.callback(self.entry.get_text())
        self.destroy()

    def __init__(self, callback):
        super().__init__(title=_("BE Name Entry"))
        self.set_resizable(False)
        self.callback = callback
        self.set_size_request(400, 25)
        box = Gtk.Box()
        self.add(box)

        self.entry = Gtk.Entry()
        box.pack_start(self.entry, True, True, 2)

        button = Gtk.Button('OK')
        button.connect("clicked", self.clicked)
        box.pack_start(button, True, True, 2)


class not_root(Gtk.Window):
    def __init__(self):
        Gtk.Window.__init__(self)
        self.set_title(_("Backup Station"))
        self.set_resizable(False)
        self.connect("delete-event", Gtk.main_quit)
        self.set_size_request(200, 80)
        box1 = Gtk.VBox(homogeneous=False, spacing=0)
        self.add(box1)
        box1.show()
        label = Gtk.Label(label=_('You need to be root'))
        box1.pack_start(label, True, True, 0)
        hBox = Gtk.HBox(homogeneous=False, spacing=0)
        hBox.show()
        box1.pack_end(hBox, False, False, 5)
        ok_button = Gtk.Button()
        ok_button.set_label("OK")
        apply_img = Gtk.Image()
        apply_img.set_from_icon_name('gtk-ok', 1)
        ok_button.set_image(apply_img)
        ok_button.connect("clicked", Gtk.main_quit)
        hBox.pack_end(ok_button, False, False, 5)
        self.show_all()


class confirmation(Gtk.Window):
    def confirm_passwd(self, widget, user):
        pwd_hash = pwd.getpwnam(user).pw_passwd
        password = self.passwd.get_text()
        if crypt.crypt(password, pwd_hash) == pwd_hash:
            self.hide()
            BackupStationWindow().show_all()
        else:
            self.hide()
            self.wrong_password()

    def wrong_password(self):
        window = Gtk.Window()
        window.set_title(_("Backup Station"))
        self.set_resizable(False)
        window.connect("delete-event", Gtk.main_quit)
        window.set_size_request(200, 80)
        box1 = Gtk.VBox(homogeneous=False, spacing=0)
        window.add(box1)
        box1.show()
        label = Gtk.Label(label=_('Wrong password'))
        box1.pack_start(label, True, True, 0)
        hBox = Gtk.HBox(homogeneous=False, spacing=0)
        hBox.show()
        box1.pack_end(hBox, False, False, 5)
        ok_button = Gtk.Button()
        ok_button.set_label("OK")
        apply_img = Gtk.Image()
        apply_img.set_from_icon_name('gtk-ok', 1)
        ok_button.set_image(apply_img)
        ok_button.connect("clicked", Gtk.main_quit)
        hBox.pack_end(ok_button, False, False, 5)
        window.show_all()

    def __init__(self, user):
        Gtk.Window.__init__(self)
        self.set_title(_("Backup Station"))
        self.set_resizable(False)
        self.connect("delete-event", Gtk.main_quit)
        self.set_size_request(200, 80)
        vBox = Gtk.VBox(homogeneous=False, spacing=0)
        self.add(vBox)
        vBox.show()
        label = _("Confirm password for")
        label = Gtk.Label(label=label + f" {user}")
        vBox.pack_start(label, True, True, 5)
        self.passwd = Gtk.Entry()
        self.passwd.set_visibility(False)
        self.passwd.connect("activate", self.confirm_passwd, user)
        hBox = Gtk.HBox(homogeneous=False, spacing=0)
        hBox.show()
        vBox.pack_start(hBox, False, False, 5)
        hBox.pack_start(self.passwd, True, True, 20)
        hBox = Gtk.HBox(homogeneous=False, spacing=0)
        hBox.show()
        vBox.pack_end(hBox, False, False, 5)
        ok_button = Gtk.Button()
        ok_button.set_label("OK")
        apply_img = Gtk.Image()
        apply_img.set_from_icon_name('gtk-ok', 1)
        ok_button.set_image(apply_img)
        ok_button.connect("clicked", self.confirm_passwd, user)
        hBox.pack_end(ok_button, False, False, 5)
        self.show_all()


if os.geteuid() == 0:
    user = os.getenv("SUDO_USER")
    if user is None:
        BackupStationWindow()
    else:
        confirmation(user)
else:
    not_root()

Gtk.main()
